// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/site-variants/Commander.tsx": () => import("../components/mockups/site-variants/Commander.tsx"),
  "./components/mockups/site-variants/Executive.tsx": () => import("../components/mockups/site-variants/Executive.tsx"),
  "./components/mockups/site-variants/Minimal.tsx": () => import("../components/mockups/site-variants/Minimal.tsx")
};
